<?php

namespace FabBundle\Repository;

/**
 * CatgMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatgMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
