<?php

namespace FabBundle\Repository;

/**
 * FabLabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabLabRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($term)
{
    return $this->createQueryBuilder('FabLab')
        ->andWhere('FabLab.nom like  :nom')
        ->setParameter('nom', '%'.$term.'%')
        ->getQuery()
        ->execute();
}
    public function search1($term)
    {
        return $this->createQueryBuilder('FabLab')
            ->andWhere('FabLab.adresse like = :adr')
            ->andWhere('FabLab.nom like  :nom')
            ->setParameter('adr', '%'.$term.'%')

            ->getQuery()
            ->execute();
    }
    public function search2($term1,$term2)
    {
        return $this->createQueryBuilder('FabLab')
            ->andWhere('FabLab.adresse like  :adr')
            ->andWhere('FabLab.nom like  :nom')
            ->setParameter('nom', '%'.$term1.'%')
            ->setParameter('adr', '%'.$term2.'%')
            ->getQuery()
            ->execute();
    }
}
