<?php

namespace FabBundle\Repository;

/**
 * FournisseurLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurLogRepository extends \Doctrine\ORM\EntityRepository
{
}
