<?php

namespace FabBundle\Repository;

/**
 * LogicielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogicielRepository extends \Doctrine\ORM\EntityRepository
{
}
