<?php

namespace FabBundle\Repository;

/**
 * MaterielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielsRepository extends \Doctrine\ORM\EntityRepository
{


    public function findDQL($id)
    {


        $q = $this->getEntityManager()
            ->createQuery("SELECT p FROM FabBundle:Magasins p
            WHERE p.Fablab.id=$id");
        return $q->getResult();
    }

        public function search($term)
    {
        return $this->createQueryBuilder('Materiels')
            ->andWhere('Materiels.nom like  :nom')
            ->setParameter('nom', '%'.$term.'%')
            ->getQuery()
            ->execute();
    }
        public function search1($term)
    {
        return $this->createQueryBuilder('Materiels')
            ->andWhere('Materiels.prix like = :prx')

            ->setParameter('prx', '%'.$term.'%')

            ->getQuery()
            ->execute();
    }
        public function search2($term1,$term2,$term3)
    {
        return $this->createQueryBuilder('Materiels')
            ->andWhere('Materiels.prix >=  :pmin')
            ->andWhere('Materiels.nom like  :nom')
            ->andWhere('Materiels.prix <=  :pmax')
            ->setParameter('nom', '%'.$term1.'%')
            ->setParameter('pmin', '%'.$term2.'%')
            ->setParameter('pmax', '%'.$term3.'%')
            ->getQuery()
            ->execute();
    }
    }
