<?php

namespace FabBundle\Repository;

/**
 * TypeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
