admin_evenement:
    path:   /evenement
    defaults: { _controller: AdminBundle:AdminEvenement:evenement}

admin_evenement_categories:
    path:   /evenement/categories
    defaults: { _controller: AdminBundle:AdminEvenement:indexCategories}

admin_evenement_events_signales:
    path:   /evenement/events_signales
    defaults: { _controller: AdminBundle:AdminEvenement:indexEvenementsSignales}

admin_evenement_events_bloques:
    path:   /evenement/events_bloques
    defaults: { _controller: AdminBundle:AdminEvenement:addCat}

admin_evenement_chart:
    path:   /evenement/chart
    defaults: { _controller: AdminBundle:AdminEvenement:chart}

admin_evenement_update_cat:
    path:   /evenement/update_cat/{id}
    defaults: { _controller: AdminBundle:AdminEvenement:updateCat}
    requirements:
        id: '[1-9][0-9]*'

admin_evenement_add_cat:
    path:   /evenement/add_cat
    defaults: { _controller: AdminBundle:AdminEvenement:addCat}

admin_evenement_delete_cat:
    path:   /evenement/add_cat/{id}
    defaults: { _controller: AdminBundle:AdminEvenement:deleteCat}
    requirements:
        id: '[1-9][0-9]*'