evenements_homepage:
    path:     /
    defaults: { _controller: evenementsBundle:Evenement:index }

evenements_homepage_filter:
    path:     /filter
    defaults: { _controller: evenementsBundle:Evenement:filter }

evenements_show_event:
    path:     /event/{id}
    defaults: { _controller: evenementsBundle:Evenement:show }
    requirements:
        id: '[1-9][0-9]*'

evenements_add_event:
    path:     /add
    defaults: { _controller: evenementsBundle:Evenement:add }

evenements_update_event:
    path:     /update/{id}
    defaults: { _controller: evenementsBundle:Evenement:update }
    requirements:
        id: '[1-9][0-9]*'

evenements_search_event:
    path:     /search
    defaults: { _controller: evenementsBundle:Evenement:search }

evenements_bookmark_event:
    path:     /bookmark
    defaults: { _controller: evenementsBundle:Evenement:bookmark }

evenements_report_event:
    path:     /report/{id}
    defaults: { _controller: evenementsBundle:Evenement:report }

evenements_add_image:
    path:     /add_image/{id}
    defaults: { _controller: evenementsBundle:Evenement:addImage }
    requirements:
        id: '[1-9][0-9]*'

evenements_delete_image:
    path:     /delete_image/{id}
    defaults: { _controller: evenementsBundle:Evenement:deleteImage }
    requirements:
        id: '[1-9][0-9]*'

evenements_toggle_inscri:
    path:     /inscri/{id}
    defaults: { _controller: evenementsBundle:Evenement:inscri }
    requirements:
        id: '[1-9][0-9]*'

evenements_delete_event:
    path:     /delete/{id}
    defaults: { _controller: evenementsBundle:Evenement:delete }
    requirements:
        id: '[1-9][0-9]*'

evenements_inscris:
    path:   /events_inscri
    defaults: { _controller: evenementsBundle:Evenement:eventsInscri }

evenements_organises:
    path:   /events_organise
    defaults: { _controller: evenementsBundle:Evenement:eventsOrganise }

evenements_enregistres:
    path:   /events_enregistre
    defaults: { _controller: evenementsBundle:Evenement:EventsEnregistre }

evenements_pdf_export:
    path:   /pdf/{id}
    defaults: { _controller: evenementsBundle:Evenement:renderPdf }    
    requirements:
        id: '[1-9][0-9]*'    

#**********************partie mobile ******************************
mobile_evenements_homepage:
    path:     /mobile/
    defaults: { _controller: evenementsBundle:EvenementMobile:index }

mobile_evenements_categories:
    path:     /mobile/categories
    defaults: { _controller: evenementsBundle:EvenementMobile:getCategories }


mobile_evenements_add:
    path:     /mobile/add
    defaults: { _controller: evenementsBundle:EvenementMobile:add }

mobile_evenements_show_event:
    path:     /mobile/event/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:show }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_add_event:
    path:     /mobile/add/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:add }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_add_image:
    path:     /mobile/addImage/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:addImage }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_update:
    path:     /mobile/update/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:update }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_delete:
    path:     /mobile/delete/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:delete }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_inscri:
    path:     /mobile/inscri/{id}/{userId}
    defaults: { _controller: evenementsBundle:EvenementMobile:inscri }
    requirements:
        id: '[1-9][0-9]*'
        userId : '[1-9][0-9]*'

mobile_evenements_organises:
    path:     /mobile/organises/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:evenementsOrganise }
    requirements:
        id: '[1-9][0-9]*'

mobile_evenements_Inscris:
    path:     /mobile/inscris/{id}
    defaults: { _controller: evenementsBundle:EvenementMobile:evenementsInscris }
    requirements:
        id: '[1-9][0-9]*'

mobile_loggin:
    path: /mobile/loggin
    defaults: {_controller: evenementsBundle:EvenementMobile:connexion}        

mobile_evenements_saved:
    path:     /mobile/isSaved/{id}/{user_id}
    defaults: { _controller: evenementsBundle:EvenementMobile:isSaved }
    requirements:
        id: '[1-9][0-9]*'
        user_id : '[1-9][0-9]*'    

mobile_evenements_toggle_save:
    path:     /mobile/toggleSaved/{id}/{user_id}
    defaults: { _controller: evenementsBundle:EvenementMobile:toggleSave }
    requirements:
        id: '[1-9][0-9]*'
        user_id : '[1-9][0-9]*'            