evenements_homepage:
    path:     /
    defaults: { _controller: evenementsBundle:Evenement:index }

evenements_add_event:
    path:     /add
    defaults: { _controller: evenementsBundle:Evenement:add }

evenements_search_event:
    path:     /search
    defaults: { _controller: evenementsBundle:Evenement:search }

evenements_bookmark_event:
    path:     /bookmark
    defaults: { _controller: evenementsBundle:Evenement:bookmark }


