# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        techEventsBundle\Entity\User: md5   
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login :
            pattern: ^/(login$|register|resetting)
            anonymous : true
            

        main: 
            anonymous: false
            pattern: ^/
            form_login:
                provider:    fos_userbundle
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }