<?php

namespace UserBundle\Repository;

/**
 * DemandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function  advancedSearch($keyword){

        $em = $this->getEntityManager();
        $repo = $em->getRepository('UserBundle:Demandes');
        $query = $repo->createQueryBuilder('d')
            ->where('d.titre LIKE :titre or d.lieu like :lieu or d.date like :date or d.eMail like :eMail')
            ->setParameter('titre', '%'.$keyword.'%')
            ->setParameter('lieu', '%'.$keyword.'%')
            ->setParameter('date', '%'.$keyword.'%')
            ->setParameter('eMail', '%'.$keyword.'%')
            ->getQuery()->getResult();
        return $query;
    }

    public function allByName(){
        $query= $this->getEntityManager()->createQuery("select d from UserBundle:Demandes d 
         where d.date> CURRENT_TIMESTAMP() order by d.titre DESC ");
        return $query->getResult();
    }

    public function allByDateModif(){
        $query= $this->getEntityManager()->createQuery("select d from UserBundle:Demandes d 
         where d.date> CURRENT_TIMESTAMP() order by d.dateModification DESC");
        return $query->getResult();
    }

    public function allByDate(){
        $query= $this->getEntityManager()->createQuery("select d from UserBundle:Demandes d
         where d.date> CURRENT_TIMESTAMP() order by d.date ASC");
        return $query->getResult();
    }


}
