<?php

namespace UserBundle\Repository;

/**
 * OffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyUserDQL($idUtilisateur)
    {
        $req =$this->getEntityManager()->createQuery("SELECT o from UserBundle:Offres o where o.idUtilisateur LIKE :idUtilisateur 
                                                           ORDER BY o.dateModif ASC");
        $req->setParameter('idUtilisateur',$idUtilisateur);
        return $req->getResult();
    }
    public function findNameDQL($nomSponsors)
    {
        $req =$this->getEntityManager()->createQuery("SELECT v from UserBundle:Offres v where v.nomSponsors LIKE :nomSponsors ");
        $req->setParameter('nomSponsors',$nomSponsors);
        return $req->getResult();
    }

    public function getSearch($nomSponsors){

        $qb = $this->createQueryBuilder('o')
            ->where('o.nomSponsors LIKE :nomSponsors')
            ->setParameter('nomSponsors', $nomSponsors)
            ->getQuery();
    }

    public function findSponsorDQL($nomSponsors)
    {
        $req =$this->getEntityManager()->createQuery("SELECT o from UserBundle:Offres o where o.nomSponsors LIKE :nomSponsors");
        $req->setParameter('nomSponsors',$nomSponsors);
        return $req->getResult();
    }

    public function  advancedSearch($keyword){

        $em = $this->getEntityManager();
        $repo = $em->getRepository('UserBundle:Offres');
        $query = $repo->createQueryBuilder('o')
            ->where('o.nomSponsors LIKE :nomSponsors or o.adresse like :adresse or o.dateModif like :dateModif or o.eMail like :eMail')
            ->setParameter('nomSponsors', '%'.$keyword.'%')
            ->setParameter('adresse', '%'.$keyword.'%')
            ->setParameter('dateModif', '%'.$keyword.'%')
            ->setParameter('eMail', '%'.$keyword.'%')
            ->getQuery()->getResult();
        return $query;
    }

    public function allByName(){
        $query= $this->getEntityManager()->createQuery("select o from UserBundle:Offres o
          order by o.nomSponsors ");
        return $query->getResult();
    }

    public function allByDateModif(){
        $query= $this->getEntityManager()->createQuery("select o from UserBundle:Offres o 
          order by o.dateModif DESC");
        return $query->getResult();
    }


}
