<?php

namespace UserBundle\Repository;

/**
 * ReclamationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byUtilisateurs($utilisateurs)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.utilisateurs = :utilisateurs')

            ->orderBy('u.id')
            ->setParameter('utilisateurs', $utilisateurs);
        return $qb->getQuery()->getResult();
    }
}
