<?php

namespace ActualBundle\Repository;
use ActualBundle\Entity\Actualite;



/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPayQB(){
        $query = $this->createQueryBuilder('s')
            ->where("s.id=:id")->setParameter('id','1');
        return $query->getQuery()->getResult();
    }

    public function findPaysDQL(){
        $query = $this->getEntityManager()->createQuery("SELECT m from ActualBundle:Actualite m Where m.id=:id")->setParameter('id','1');
        return $query->getResult();
    }


}
