<?php

namespace ActualBundle\Repository;
use ActualBundle\Entity\Opportunite;



/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportuniteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPayQB(){
        $query = $this->createQueryBuilder('s')
            ->where("s.pays=:pays")->setParameter('pays','Allemande');
        return $query->getQuery()->getResult();
    }

    public function findPaysDQL(){
        $query = $this->getEntityManager()->createQuery("SELECT m from EspritParcBundle:Modele m Where m.pays=:pays")->setParameter('pays','allemagne');
        return $query->getResult();
    }


}
