<?php

namespace evenementsBundle\Repository;

/**
 * EventSignalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSignalesRepository extends \Doctrine\ORM\EntityRepository
{
}
