<?php

namespace evenementsBundle\Repository;

/**
 * ImageEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
